[package]
name = "bichano"
version = "0.1.0"
authors = ["ratosh <ratosh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgn-reader = "0.15.0"
shakmaty = "0.15"