[package]
name = "network"
version = "0.1.0"
authors = ["ratosh <ratosh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shakmaty = "0.15"
pgn-reader = {path = "../rust-pgn-reader"}