# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training_chunk.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='training_chunk.proto',
  package='protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x14training_chunk.proto\x12\x06protos\"k\n\nBoardChunk\x12\x31\n\x08\x65ncoding\x18\x01 \x02(\x0e\x32\x1f.protos.BoardChunk.EncodingType\x12\x0e\n\x06planes\x18\x02 \x03(\x04\"\x1a\n\x0c\x45ncodingType\x12\n\n\x06SIMPLE\x10\x00\"0\n\x0bPolicyChunk\x12\x12\n\nmove_index\x18\x01 \x02(\r\x12\r\n\x05value\x18\x02 \x02(\x02\"\xb5\x01\n\rPositionChunk\x12:\n\x08\x65ncoding\x18\x01 \x02(\x0e\x32(.protos.PositionChunk.PolicyEncodingType\x12!\n\x05\x62oard\x18\x02 \x02(\x0b\x32\x12.protos.BoardChunk\x12#\n\x06policy\x18\x03 \x03(\x0b\x32\x13.protos.PolicyChunk\" \n\x12PolicyEncodingType\x12\n\n\x06SIMPLE\x10\x00\"Z\n\tGameChunk\x12(\n\tpositions\x18\x01 \x03(\x0b\x32\x15.protos.PositionChunk\x12#\n\x06result\x18\x02 \x01(\x0e\x32\x13.protos.ResultChunk\")\n\x05\x43hunk\x12 \n\x05games\x18\x01 \x03(\x0b\x32\x11.protos.GameChunk*-\n\x0bResultChunk\x12\t\n\x05WHITE\x10\x00\x12\t\n\x05\x42LACK\x10\x01\x12\x08\n\x04\x44RAW\x10\x02'
)

_RESULTCHUNK = _descriptor.EnumDescriptor(
  name='ResultChunk',
  full_name='protos.ResultChunk',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WHITE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLACK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAW', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=510,
  serialized_end=555,
)
_sym_db.RegisterEnumDescriptor(_RESULTCHUNK)

ResultChunk = enum_type_wrapper.EnumTypeWrapper(_RESULTCHUNK)
WHITE = 0
BLACK = 1
DRAW = 2


_BOARDCHUNK_ENCODINGTYPE = _descriptor.EnumDescriptor(
  name='EncodingType',
  full_name='protos.BoardChunk.EncodingType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SIMPLE', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=113,
  serialized_end=139,
)
_sym_db.RegisterEnumDescriptor(_BOARDCHUNK_ENCODINGTYPE)

_POSITIONCHUNK_POLICYENCODINGTYPE = _descriptor.EnumDescriptor(
  name='PolicyEncodingType',
  full_name='protos.PositionChunk.PolicyEncodingType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SIMPLE', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=341,
  serialized_end=373,
)
_sym_db.RegisterEnumDescriptor(_POSITIONCHUNK_POLICYENCODINGTYPE)


_BOARDCHUNK = _descriptor.Descriptor(
  name='BoardChunk',
  full_name='protos.BoardChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encoding', full_name='protos.BoardChunk.encoding', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='planes', full_name='protos.BoardChunk.planes', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BOARDCHUNK_ENCODINGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=139,
)


_POLICYCHUNK = _descriptor.Descriptor(
  name='PolicyChunk',
  full_name='protos.PolicyChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='move_index', full_name='protos.PolicyChunk.move_index', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='protos.PolicyChunk.value', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=189,
)


_POSITIONCHUNK = _descriptor.Descriptor(
  name='PositionChunk',
  full_name='protos.PositionChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encoding', full_name='protos.PositionChunk.encoding', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='board', full_name='protos.PositionChunk.board', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='policy', full_name='protos.PositionChunk.policy', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POSITIONCHUNK_POLICYENCODINGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=373,
)


_GAMECHUNK = _descriptor.Descriptor(
  name='GameChunk',
  full_name='protos.GameChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='protos.GameChunk.positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='protos.GameChunk.result', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=465,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='protos.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='games', full_name='protos.Chunk.games', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=508,
)

_BOARDCHUNK.fields_by_name['encoding'].enum_type = _BOARDCHUNK_ENCODINGTYPE
_BOARDCHUNK_ENCODINGTYPE.containing_type = _BOARDCHUNK
_POSITIONCHUNK.fields_by_name['encoding'].enum_type = _POSITIONCHUNK_POLICYENCODINGTYPE
_POSITIONCHUNK.fields_by_name['board'].message_type = _BOARDCHUNK
_POSITIONCHUNK.fields_by_name['policy'].message_type = _POLICYCHUNK
_POSITIONCHUNK_POLICYENCODINGTYPE.containing_type = _POSITIONCHUNK
_GAMECHUNK.fields_by_name['positions'].message_type = _POSITIONCHUNK
_GAMECHUNK.fields_by_name['result'].enum_type = _RESULTCHUNK
_CHUNK.fields_by_name['games'].message_type = _GAMECHUNK
DESCRIPTOR.message_types_by_name['BoardChunk'] = _BOARDCHUNK
DESCRIPTOR.message_types_by_name['PolicyChunk'] = _POLICYCHUNK
DESCRIPTOR.message_types_by_name['PositionChunk'] = _POSITIONCHUNK
DESCRIPTOR.message_types_by_name['GameChunk'] = _GAMECHUNK
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.enum_types_by_name['ResultChunk'] = _RESULTCHUNK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoardChunk = _reflection.GeneratedProtocolMessageType('BoardChunk', (_message.Message,), {
  'DESCRIPTOR' : _BOARDCHUNK,
  '__module__' : 'training_chunk_pb2'
  # @@protoc_insertion_point(class_scope:protos.BoardChunk)
  })
_sym_db.RegisterMessage(BoardChunk)

PolicyChunk = _reflection.GeneratedProtocolMessageType('PolicyChunk', (_message.Message,), {
  'DESCRIPTOR' : _POLICYCHUNK,
  '__module__' : 'training_chunk_pb2'
  # @@protoc_insertion_point(class_scope:protos.PolicyChunk)
  })
_sym_db.RegisterMessage(PolicyChunk)

PositionChunk = _reflection.GeneratedProtocolMessageType('PositionChunk', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONCHUNK,
  '__module__' : 'training_chunk_pb2'
  # @@protoc_insertion_point(class_scope:protos.PositionChunk)
  })
_sym_db.RegisterMessage(PositionChunk)

GameChunk = _reflection.GeneratedProtocolMessageType('GameChunk', (_message.Message,), {
  'DESCRIPTOR' : _GAMECHUNK,
  '__module__' : 'training_chunk_pb2'
  # @@protoc_insertion_point(class_scope:protos.GameChunk)
  })
_sym_db.RegisterMessage(GameChunk)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'training_chunk_pb2'
  # @@protoc_insertion_point(class_scope:protos.Chunk)
  })
_sym_db.RegisterMessage(Chunk)


# @@protoc_insertion_point(module_scope)
